- client/index.html
- client/package.json
- client/src/main.tsx
- client/src/pages/GeneralInfo/GeneralInfo.module.scss
- client/src/pages/GeneralInfo/GeneralInfo.tsx
- client/src/pages/index.ts
- package-lock.json
This PR introduces a new General Info page that is part of the user registration process. It allows new users to input their general information, such as name, username, email, phone number, and date of birth.
- **New Components:**
- `GeneralInfo`: The main component for the general information form.
- **State Management:**
- Utilized React's `useState` for handling form inputs including first name, last name, username, email, phone number, and date of birth.
- **Form Inputs:**
- Implemented a reusable `TextField` component for various inputs with validation for email and phone formats.
- **Styling:**
- Applied styles using `GeneralInfo.module.scss`. Added a Google Font called 'Lato' and changed the weight to match the Figma design better.
- **Material UI Integration:**
- Used Material UI …
> Added General Info Page for Registration

- client/src/components/LocationNotification/LocationNotification.module.scss
- client/src/components/LocationNotification/LocationNotification.tsx
- client/src/components/index.ts
This PR closes #25.
This PR seeks to create and implement a simple Component that will appear at the front of the user's screen, that prompts the user for access to their Location services. Currently, the frontend work has been completed. 
Next steps are to implement the button components' functionality, specifically using the useLocation hook. This can be accomplished with a future PR. 
Currently, the image used is our Roadwatch logo, and in a future PR this can be changed to a specific icon if need be.
This was tested by just creating the LocationNotification component in a page, and the results had it hovering above the other text and components. 
Preview of the component:
Your feedback is greatly appreciated and thank you!
> LocationNotification Component Front End

- client/package.json
- client/src/main.tsx
- client/src/pages/GeneralInfo/GeneralInfo.tsx
- client/src/pages/SignUp/SignUp.tsx
- package-lock.json
I'm hosting the app on vercel but we are having some build issues.
The issues involve unused variables, a missing {, and a missing package.
I have added all of the missing items in this PR.
I have simply console logged all unused variables so that they are become used.
1 file has a few more changes cause of prettier formatting.
This builds on my machine so I hope it builds well on vercel with these changes.
> Fix for vercel build

- client/src/main.tsx
- client/src/pages/SignUp/GeneralInfo/GeneralInfo.tsx
This should fix the deployment error from my last PR and address issue #70 
Changes Made:
Took out any unused variables found in the linting errors found during last PR merge.
> Fixed linting errors

- client/package.json
- client/src/main.tsx
- client/src/pages/Instructions/Instructions.module.scss
- client/src/pages/Instructions/Instructions.tsx
- client/src/pages/index.ts
- package-lock.json
* Instructions Page Updates
Added two new files:
- Instructions.tsx
- Instructions.module.scss
Also added the route to Instructions in main.tsx.
* Updated Instructions Page
Started the basic outline of the Instructions Page.
* Updated instructionsPage
There is now a fully functioning instructions page.
* Update package.json
Added the mui carousel package
* Update Instructions.tsx
Removed unused image imports.
> Instructions page (#65)

- client/src/pages/CreateAccount/CreateAccount.tsx
- client/src/pages/SignUp/GeneralInfo/GeneralInfo.tsx
- client/src/pages/SignUp/SignUp.tsx
- package-lock.json
This pull request implements required field validation for the SignUp form (including the Create Account, SignUp, and General Info pages). It ensures that users must fill in all required fields before continuing.
This PR addresses issue #83 
The `handleClick` and `onClick` functions now check if all required fields are filled in before allowing the user to continue. This improves the user experience by ensuring data integrity.
> Add Mandatory Input Fields to Sign Up Pages

- .github/workflows/jest.yml
- .github/workflows/testing.yml
This will allow us to have streamlined unit testing, as well as make sure that all the code that is written will not negatively impact previously written code. It will automatically run our Jest testing, as well as coverage reports.
This PR performs both Vitest and Jest testing, so it covers the client and server side testing
This PR closes #90 and #92
This is a workflow addition(not sure what that falls under).
Currently, the testing is very limited, so new testing will be needed to be added in future PRs
> Add workflow for Jest and Vitest testing

- server/src/controllers/MarkerController.ts
- server/src/index.ts
- server/src/routes/Marker.ts
This PR adds in back end functionality for the creation of markers on the map. The database will now have entries for when a marker is created(POST), and we can also delete the markers as well(DELETE). Also, all the markers on the map can be queried by a GET request, so that we can update our map with the markers that the users have created. 
This PR closes #98 
This PR adds in backend support for markers on the map
POST request to add a marker in
GET request to see all the markers saved
DELETE request to remove the marker
GET request after the marker was deleted
ChatGPT was utilized in order to add useful comments and documentation to the code …
> Add Marker server endpoints

- client/vercel.json
Vercel was having issues with different routes with react router
closes #117 
[Describe any changes here]
Register page now properly shows
Vercel has some problems with figuring out where routes are and where they go using react router.
This stackoverflow discussion is what this PR incorporates: https://stackoverflow.com/questions/64815012/why-does-react-router-not-works-at-vercel
> Fix Vercel 404

- client/src/store/community/community.slice.ts
- client/src/store/community/index.ts
- client/src/types/types.ts
- server/src/controllers/CommunityController.ts
- server/src/index.ts
- server/src/routes/Community.ts
In this PR, I created a GET endpoint for acquiring all the communities currently stored in the database. This will be extremely helpful later on as we develop our Community page (#110). 
This PR closes #49 and should be used in #110. 
- Created a route in Express for getting all the communities: `/api/community/all-communities`.
- Created a controller to handle querying the database for all communities.
- Created a slice that can be used to the call the endpoint on the client.
- Created type interfaces for all our models so our response types are more accurate.
I wasn't able to test this thoroughly since we don't have a way to create communities yet. We might have to …
> Created Community GET Endpoint

- client/src/store/post/index.ts
- client/src/store/post/post.slice.ts
- package-lock.json
- server/src/controllers/PostController.ts
- server/src/index.ts
- server/src/routes/Post.ts
This pull request introduces several key updates to the endpoints for handling posts.
Changes include:
- Added getAllPosts Query endpoint
- Added savePost Mutation endpoint
- Added deletePost Mutation endpoint
- Added AI documentation
Closes #99
The new features include the ability to add and save posts through new endpoints.
In future updates, the following items might need attention:
Please refer to screenshot attached for testing with postman.
Only the endpoints have been added, needs to be tied to the front end.
> Post server endpoints

- client/src/components/CreateAccount/CreateAccount.tsx
- client/src/components/SignUp/GeneralInfo/GeneralInfo.tsx
- client/src/pages/Register/Register.tsx
This PR implements the backend functionality for the register page.
Closes #108 
Uses the createUser mutation to create the user after they input all the information
Here is a short video showing the complete register process, including how to log in after the user is created.
https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/105743189/2ebbf53f-5e19-4e61-9359-a84b6f2e1042
Note how the home page displays the correct username.
The implementation was enhanced through ChatGPT, and was instrumental throughout the troubleshooting process. Here is the relevant conversation: https://chat.openai.com/share/429fa8c9-a667-4f21-98da-fb980a68dcb9
AI-generated code has …
> Create Backend for Register Page

- client/src/pages/ResetPassword/ResetPassword.tsx
- client/tests/pages/ResetPassword/ResetPassword.test.tsx
This PR creates a unit test for the Reset Password page
Closes #144 
The unit tests were written using ChatGPT. That conversation can be found [here](https://chat.openai.com/share/c8af70a0-b41d-4e09-a53e-84c0a0d8a3f0)
> Unit test for ResetPassword

- client/src/pages/Forgot/Forgot.tsx
- client/tests/pages/Forgot/Forgot.test.tsx
This PR creates a unit test for the Forgot page 
Closes #142 
The unit tests were written using ChatGPT. That conversation can be found [here](https://chat.openai.com/share/b6a97f36-4119-4fc1-b3c9-982847720f99)
> Unit test for Forgot page

- client/src/pages/Instructions/Instructions.tsx
- client/tests/pages/Instructions/Instructions.test.tsx
This PR creates a unit test for the Instructions page.
Closes #149 
The unit tests were written using ChatGPT. The conversation can be found [here](https://chat.openai.com/share/4c25d0e9-1559-40d2-8af8-74943a655460).
> Unit testing for Instructions page

- client/src/components/CommunityCard/CommunityCard.tsx
- client/src/components/Header/Header.tsx
- client/src/components/ProfileIcon/ProfileIcon.tsx
- client/src/components/index.ts
- client/src/pages/Instructions/Instructions.tsx
- client/tests/pages/Instructions/Instructions.test.tsx
Adding recent code from main into my branch
[Reference any related issues being addressed by this pull request, e.g., "Closes #123"]
Adding recent code from main into my branch
[Insert any relevant screenshots or GIFs to showcase visual changes, if applicable]
[Provide any additional information or context for reviewers]
> Merging main to 152-slice-for-markers

- client/src/components/Navbar/Navbar.module.scss
- client/src/components/Navbar/Navbar.tsx
This pull request updates the style of the `navbar` component that is used at the bottom of the site to match the design established throughout the rest of the site. 
This pull request closes #127 and addresses #126. 
The update includes matching the same color of orange that is used throughout the rest of the site, setting the font of the labels to Roboto or Open Sans, and changing the font color of the labels to black so it matches the theme of the site.
I utilized issue #126 as a reference while implementing the font family Roboto or Open Sans. To achieve this, I directly imported the `index.css` file into the SCSS module of the `navbar` component. This approach …
> Style update: `Navbar` component

- client/src/store/api/api.slice.ts
- server/src/config/database.ts
Fix the api slice bug I introduced
closes #159
[Describe any changes here]
[Insert any relevant screenshots or GIFs to showcase visual changes, if applicable]
[Provide any additional information or context for reviewers]
> fix api slice and database config

- client/src/components/Security/UpdatePassword/UpdatePassword.module.scss
- client/src/components/Security/UpdatePassword/UpdatePassword.tsx
- client/src/components/UserProfileUpdate/UserProfileUpdate.module.scss
- client/src/components/UserProfileUpdate/UserProfileUpdate.tsx
- client/src/pages/SettingsPage/SettingsPage.tsx
- client/src/store/user/user.slice.ts
- server/src/controllers/UserController.ts
- server/src/routes/User.ts
This pull request introduces two new components aimed at improving the user settings page:
- Update Password component
- Update Profile Component
These components have been added to enhance the settings page, allowing users to update their passwords and profiles more efficiently.
In future iterations, the following elements might need updates or further enhancements:
Please review the new components added to the settings page. Feedback on design and functionality improvements is highly appreciated to further refine user interactions.
> Update Password and Update Profile Components for Settings Page

- client/src/pages/Register/Register.tsx
- client/tests/pages/Register/Register.test.tsx
This PR creates a unit test for the Register page
Closes #153 
This was written using chatGPT: https://chat.openai.com/share/27df000c-106f-4e10-b27c-fdf04a3910b3
> unit test for register page

- client/src/components/Header/Header.module.scss
- client/src/components/Header/Header.tsx
- client/src/pages/Home/Home.tsx
- client/src/store/marker/marker.slice.ts
- server/src/controllers/MarkerController.ts
- server/test/routes/marker.test.ts
[Provide a brief description of the changes introduced by this pull request]
After submitting our last batch of PRs tonight, I realized that many features that were working perfectly before were now extremely broken. This was likely due to a lack of communication on our parts and merge conflicts that were not handled properly.
[Reference any related issues being addressed by this pull request, e.g., "Closes #123"]
There's no point in creating an issue. These are extremely quick fixes.
The following changes have been implemented:
- Fixed the `Marker` API to hit the correct route.
- Moved the `SpeedDial` on the home page up a bit so it's not bleeding onto the `Navbar`.
- Repositioned the Logout button so it's not bleeding onto the map.
- Fixed an issue …
> Final Fixes (Style + Functionality)

- client/src/components/Navbar/Navbar.tsx
This was previously reverted in one of the final PRs.
> Fixed navigation to Settings page.
